# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-28 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Nothing'), (1, 'Correct'), (2, 'Wrong'), (3, 'Rectify')])),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_info', models.CharField(max_length=100)),
                ('field', models.IntegerField(choices=[(0, 'Name'), (1, 'Pan No'), (2, 'dob')])),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to=b'')),
                ('confidence_level', models.IntegerField()),
                ('check_count', models.IntegerField(default=0)),
                ('verified', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.Kyc')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='masterfeedback',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.Moderator'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.Merchant'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.MasterFeedBack'),
        ),
    ]
