# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-29 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_auto_20171028_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
